apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: g7nhjhvuk-python 
  janus-idp.io/tekton: g7nhjhvuk-python
  backstage.io/kubernetes-id: g7nhjhvuk-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: g7nhjhvuk-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  